### ISSUE TITLE
Improve mirror registry logics

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/nydus#1041]
Currently, mirror registry is implemented in low-level http transport connection layer. In such a case, it is hard to handle the scenario that the redirected URL has format `foo/bar/v2/blobs/xxxx` when accessing the mirror registry which does not have the resources, and 404 is returned.

We'd better move the mirror registry to a higher level and make it only work for registry storage backend.

**Comment by imeoer** [comment]
It has been improved on latest nydusd.
