### ISSUE TITLE
ctr-remote is poorly maintained and currently uses many deprecated APIs

### ISSUE THREAD

**Issue by adamqqqplay** [dragonflyoss/nydus#1190]
ctr-remote has only upgraded dependency related maintenance for a long time, in a recent dependency upgrade, golangci-lint reported many deprecated API calls: https://github.com/dragonflyoss/image-service/actions/runs/4571843533/jobs/8070513996

```
golangci-lint run
Error: commands/rpull.go:94:3: SA1019: containerd.WithSchema1Conversion is deprecated: use Schema 2 or OCI images. (staticcheck)
		containerd.WithSchema1Conversion,
		^
Error: cmd/main.go:30:2: SA1019: seed.WithTimeAndRand is deprecated: Do not rely on the global seed. (staticcheck)
	seed.WithTimeAndRand()
	^
Error: cmd/main.go:24:2: SA1019: "github.com/containerd/containerd/pkg/seed" is deprecated: Do not rely on the global seed. (staticcheck)
	"github.com/containerd/containerd/pkg/seed"
	^
```

We should replace these deprecated APIs in the future, otherwise it may not be compatible with containerd 1.7.

**Comment by changweige** [comment]
Do we still need ctr-remote?

**Comment by imeoer** [comment]
Maybe the nerdctl support is enough for users.

**Comment by adamqqqplay** [comment]
Maybe we could migrate `ctr-remote` to `nydusify rpull` to reduce maintenance cost, like soci: https://github.com/awslabs/soci-snapshotter/blob/main/docs/getting-started.md#lazily-pull-image

**Comment by imeoer** [comment]
> Maybe we could migrate ctr-remote to nydusify rpull to reduce maintenance cost, like soci

We still need to provide `run` command etc, better to use nerdctl as the replacement.

**Comment by adamqqqplay** [comment]
> > Maybe we could migrate ctr-remote to nydusify rpull to reduce maintenance cost, like soci
> 
> We still need to provide `run` command etc, better to use nerdctl as the replacement.

Yeah, that sounds great.
