### ISSUE TITLE
Use thiserror crate to simply errors across the repo

### ISSUE THREAD

**Issue by liubogithub** [dragonflyoss/nydus#121]
Errors like `DaemonError`, `RafsError` can be simplified with the abilities provided in `thiserror` crate.

For instance, display, from can be derived directly if using thiserror.

**Comment by changweige** [comment]
Thanks for your suggestion. It sounds like a good idea.

**Comment by adamqqqplay** [comment]
#1027 PR seems to have resolved this issue

**Comment by imeoer** [comment]
It seems only part of them be handled in https://github.com/dragonflyoss/image-service/pull/1027 ?

**Comment by imeoer** [comment]
Addition: the target of using `thiserror & andhow` is to remove the `api/src/error.rs` file.
