### ISSUE TITLE
action: nydus-integration-test failed unexpected

### ISSUE THREAD

**Issue by Desiki-high** [dragonflyoss/nydus#1247]
### We run smoke test twice in https://github.com/dragonflyoss/image-service/commit/a78db8ba4ab7d800838b4f76c50b388efa3dc6be.
- failed: https://github.com/dragonflyoss/image-service/actions/runs/4781856432/attempts/1
- passed: https://github.com/dragonflyoss/image-service/actions/runs/4781856432

#### With the same code, why the first test failed but the second passed?

**Comment by adamqqqplay** [comment]
This happens often, and a rerun is usually fine.

**Comment by Desiki-high** [comment]
dropped in favor of #1515
