### ISSUE TITLE
support nydus commit operation

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/nydus#1307]
For a running container with a nydus image, we can support container commit just like `docker commit`, the commit operation packs the container writable layer as a new image.

References:

cgroup freezer: https://www.kernel.org/doc/Documentation/cgroup-v1/freezer-subsystem.txt
nerdctl commit: https://github.com/containerd/nerdctl/blob/main/pkg/imgutil/commit/commit.go#L67

We can support it in `nydusify commit` or `nerdctl commit`.

**Comment by ywcYY** [comment]
Received, currently interpreting the commit part of the code

**Comment by imeoer** [comment]
@PerseidMeteor are working on https://github.com/nydusaccelerator/nydus-cli

**Comment by PerseidMeteor** [comment]
This issue can closed by https://github.com/dragonflyoss/nydus/pull/1543
