### ISSUE TITLE
remove useless registry backend in nydusify

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/nydus#1403]
It seems we only depend on the `registry` backend type in `nydusify pack` subcommand, let's remove it from `convert/check...` subcommands.

**Comment by An-DJ** [comment]
It seems that each subcmd get backend type from args by `getBackendConfig()`, but `registry` is NOT permitted:

https://github.com/dragonflyoss/nydus/blob/master/contrib/nydusify/cmd/nydusify.go#L81

```go
func getBackendConfig(c *cli.Context, suffix string, required bool) (string, string, error) {
	backendType := c.String(suffix + "backend-type")
	if backendType == "" {
		if required {
			return "", "", errors.Errorf("backend type is empty, please specify option '--%sbackend-type'", suffix)
		}
		return "", "", nil
	}

	possibleBackendTypes := []string{"oss", "s3"}
	if !isPossibleValue(possibleBackendTypes, backendType) {
		return "", "", fmt.Errorf("--%sbackend-type should be one of %v", suffix, possibleBackendTypes)
	}
// ...
}
```

Maybe `registry` had been removed in https://github.com/dragonflyoss/nydus/commit/dc83f582f5da46d0a0f22b251e678440d5ae2d84 ?

**Comment by imeoer** [comment]
@An-DJ Ops, let's close it, thanks!
