### ISSUE TITLE
change repo name to nydus

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/nydus#1405]
Hi CNCF community operators, we are requesting to change the sub-project repo name `image-serivice` (https://github.com/dragonflyoss/image-service) of dragonfly (https://github.com/dragonflyoss/Dragonfly2) to `nydus`.

The meaning of repo name `image-service` is relatively vague and does not leave a deep impression for users. In fact, we have used `nydus` as the project name in the docs and some publicity, let's change the repo name now. Please help assess the proposal's feasibility and give a +1 or LGTM in the comment on this issue, and then I will update the repo name in github setting page, thanks!

**Comment by imeoer** [comment]
cc @krook :)

**Comment by krook** [comment]
Sounds good to me!

**Comment by imeoer** [comment]
@krook Thanks!

Let's change the repo name to `nydus`.

cc @jiangliu @bergwolf @changweige @liubogithub @hsiangkao @eryugey @adamqqqplay @sctb512
