### ISSUE TITLE
nydusd failover and live upgrade in fuse dev

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/nydus#1421]
- Failover: in the event of a nydusd crash or other failures, the nydusd process can be restarted from a snapshot. This will ensure that the container filesystem served by nydusd is still available.

- Live upgrade: nydusd can be upgraded without disrupting the container filesystem it serves. This is done by creating a snapshot of the running nydusd process, upgrading the binary, and then restoring the snapshot.

To achieve these capabilities, nydusd needs to store the following information in a persistent store:

- The fuse file descriptor for the fuse connection;
- The fuse state in [fuse-backend-rs](https://github.com/cloud-hypervisor/fuse-backend-rs);

The [nydus-snapshotter](https://github.com/containerd/nydus-snapshotter) will be responsible for the workflow.

**Comment by imeoer** [comment]
cc @loheagn

**Comment by loheagn** [comment]
https://github.com/dragonflyoss/nydus/pull/1487 and https://github.com/dragonflyoss/nydus/pull/1529 may fix this issue.
