### ISSUE TITLE
nydusd can't mount with dummycache backend

### ISSUE THREAD

**Issue by vishvananda** [dragonflyoss/nydus#1456]
## Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

### Version of nydus being used (nydusd --version)

Version:        v2.2.3
Git Commit:     e8c324687a472243d4dedadafd7fda63044aa8ac
Build Time:     2023-10-27T17:42:24.203378048Z
Profile:        release
Rustc:          rustc 1.66.1 (90743e729 2023-01-10)

### Version of nydus-snapshotter being used (containerd-nydus-grpc --version)

not using it

### Kernel information (uname -r)

6.2.0-1012-aws

### GNU/Linux Distribution, if applicable (cat /etc/os-release)

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

## Details about issue

Using the following config, nydusd is perfectly serving images
```
{
  "device": {
    "backend": {
      "type": "localfs",
      "config": {
        "dir": "/home/ubuntu/ebs/blobs"
      }
    },
    "cache": {
      "type": "blobcache",
      "config": {
        "work_dir": "/home/ubuntu/ebs/cache"
      }
    }
  },
  "mode": "direct",
  "digest_validate": false,
  "iostats_files": false,
  "enable_xattr": true
}
```
command line:
```
sudo nydusd --config nydusd-config.localfs.json --bootstrap blobs/6788acafb778c0e94f81512e133b0e2367ce13d6e63501b924008dbbe73c63ba --log-level trace --mountpoint mount
```
When I attempt to run with the dummycache backend, the bootstrap fails:
```
{
  "device": {
    "backend": {
      "type": "localfs",
      "config": {
        "dir": "/home/ubuntu/ebs/blobs"
      }
    },
    "cache": {
      "type": "dummycache"
    }
  },
  "mode": "direct",
  "digest_validate": false,
  "iostats_files": false,
  "enable_xattr": true
}
```
output:
```
[2023-10-27 17:40:01.177295 +00:00] INFO Program Version: v2.2.3, Git Commit: "e8c324687a472243d4dedadafd7fda63044aa8ac", Build Time: "2023-10-27T17:30:34.284507956Z", Profile: "release", Rustc Version: "rustc 1.66.1 (90743e729 2023-01-10)"
[2023-10-27 17:40:01.177337 +00:00] INFO Set rlimit-nofile to 1000000, maximum 1000000
[2023-10-27 17:40:01.177600 +00:00] DEBUG [/fuse-backend-rs-0.10.5/src/api/pseudo_fs.rs:161] pseudo fs iterate "/"
[2023-10-27 17:40:01.177770 +00:00] ERROR [/src/error.rs:22] Error:
        "unsupported cache type 'dummycache'"
        at api/src/config.rs:1082
        note: enable `RUST_BACKTRACE=1` env to display a backtrace
[2023-10-27 17:40:01.177787 +00:00] ERROR [/src/error.rs:22] Error:
        "failed to parse configuration information"
        at api/src/config.rs:243
        note: enable `RUST_BACKTRACE=1` env to display a backtrace
[2023-10-27 17:40:01.177801 +00:00] ERROR [/src/error.rs:22] Error:
        Rafs(LoadConfig(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
        at service/src/lib.rs:121
        note: enable `RUST_BACKTRACE=1` env to display a backtrace
[2023-10-27 17:40:01.178073 +00:00] ERROR [src/bin/nydusd/main.rs:539] Failed in starting daemon: Invalid argument (os error 22)
```
I'm attempting to performance test reading directly from the backend without local disk caching. Am I doing something wrong?

**Comment by imeoer** [comment]
It seems the rafs v6 (`nydus-image create --fs-version 6`) doesn't support the dummy cache? @jiangliu

**Comment by adamqqqplay** [comment]
> It seems the rafs v6 (`nydus-image create --fs-version 6`) doesn't support the dummy cache? @jiangliu

@imeoer In our previous tests, rafs v6 does not support dummy cache. 

@vishvananda You can use rafs v5 to work around. (Create image with `nydus-image create --fs-version 5`)

**Comment by vishvananda** [comment]
@adamqqqplay I've tried with `nydus-image create -t dir-rafs -v5 -D ../blobs rootfs` And I still get the above error with v2.2.3

**Comment by imeoer** [comment]
@vishvananda Sorry for the unverified answer :(, the bug should be fixed in https://github.com/dragonflyoss/nydus/pull/1458.

The usage steps:

```
cargo build --release

sudo ./target/release/nydus-image create \
  --fs-version 5 \
  --bootstrap /path/to/bootstrap \
  --blob-dir /path/to/blobs \
  /path/to/SOURCE

sudo ./target/release/nydusd \
  --config /path/to/nydusd-config.json \
  --bootstrap /path/to/bootstrap \
  --mountpoint /path/to/mountpoint
```
