### ISSUE TITLE
Use P2P (Dragonfly2) for all image types

### ISSUE THREAD

**Issue by PKizzle** [dragonflyoss/nydus#1478]
Currently only RAFSv6 images are mirrored or proxied to Dragonfly2. This shall be extended to all image types (OCI).
Maybe this can be added as part of nydus-overlayfs?

**Comment by imeoer** [comment]
For OCI v1 image with P2P, should just only need to configure the containerd, reference https://d7y.io/docs/setup/runtime/containerd/
