### ISSUE TITLE
feat: add the coverage statistics of go modules to codecov

### ISSUE THREAD

**Issue by Desiki-high** [dragonflyoss/nydus#1517]
## Additional Information
https://github.com/dragonflyoss/nydus/blob/45331d5e181398020b469f2d723fa92f5d28ce7e/Makefile#L130-L131
https://github.com/dragonflyoss/nydus/blob/45331d5e181398020b469f2d723fa92f5d28ce7e/.github/workflows/smoke.yml#L190-L199
![image](https://github.com/dragonflyoss/nydus/assets/59167816/46298a2f-689e-4087-a7ad-84804364d165)

## Details about issue
Now we're only adding the coverage of the rust portion. We need to also add the coverage statistics of go modules to `codecov` such as https://github.com/dragonflyoss/nydus/tree/master/contrib/nydusify.

**Comment by Desiki-high** [comment]
cc @adamqqqplay.

**Comment by Desiki-high** [comment]
dropped in favor of https://github.com/dragonflyoss/nydus/issues/1518.

**Comment by adamqqqplay** [comment]
> PTAL @adamqqqplay. You can put your work suggestions on this issue directly.

Sorry, I opened a new duplicate issue, thanks for your quick response.
