### ISSUE TITLE
Need add go module unit coverage statistics in Codecov

### ISSUE THREAD

**Issue by adamqqqplay** [dragonflyoss/nydus#1518]
Currently, only rust code is included in codecov's test coverage statistics. We should also count the coverage of go modules such as nydusify, so that we can better understand the overall test coverage of the nydus project.

Steps that may be needed:
1. Enhance makefiles such as nydusify.
2. Add a new step in .github/workflows/smoke.yml to get go module coverage.
3. Modify .github/codecov.yml.

Reference: https://github.com/dragonflyoss/nydus/pull/1228

**Comment by Desiki-high** [comment]
I will complete it later.
