### ISSUE TITLE
CreateContainerError: failed to create containerd container: taking runtime copy of volume: failed to copy files: copy file range failed: invalid argument

### ISSUE THREAD

**Issue by lihuawei321** [dragonflyoss/nydus#1553]
## Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

### Kernel information (uname -r)
_command result: 5.17

### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_

### containerd-nydus-grpc command line used, if applicable (ps aux | grep containerd-nydus-grpc)
```
root       12919  0.6  0.3 1732712 55748 ?       Ssl  Feb29   6:23 /usr/bin/containerd-nydus-grpc --config /etc/nydus/config.toml
root     1089530  0.0  0.0 112832  2292 pts/0    S+   10:09   0:00 grep --color=auto containerd-nydus-grpc
```

### client command line used, if applicable (such as: nerdctl, docker, kubectl, ctr)
```
kubectl
```

## Details about issue

在k8s里部署deployment时候，报错：
CreateContainerError: failed to create containerd container: taking runtime copy of volume: failed to copy files: copy file range failed: invalid argument

但是节点上使用nerdctl启动镜像是可以的
<img width="1111" alt="image" src="https://github.com/dragonflyoss/nydus/assets/31987918/79432570-d57c-442e-a5e5-764ab36bdf12">

**Comment by imeoer** [comment]
Are there any error messages on the nydus snapshotter logs?

**Comment by imeoer** [comment]
No detailed information is provided at the moment, open again if necessary.
