### ISSUE TITLE
nydusd thread/memory leaked after umount

### ISSUE THREAD

**Issue by ccx1024cc** [dragonflyoss/nydus#1570]
Multiple uses of the mount/umount API can lead to thread and memory leaks, with initial investigations indicating that some **prefetch** threads are not be released after umount.

**Comment by Desiki-high** [comment]
# Reproduce
## 1. Prepare test work env.
To generate test files, use `TestPrefetrch` in `smoke/api_test.go`.
![Untitled](https://github.com/user-attachments/assets/712f03d4-ef99-432f-98a0-5bcc68cea485)
## 2. Create a nydusd process.
```sudo nydusd --apisock api.sock --config nydusd-config.fusedev.json --mountpoint mnt```
Observe the number of threads of the nydusd process:
![1](https://github.com/user-attachments/assets/c77843e6-1d90-467c-bfee-dfd767263d19)
## 3. Use the mount api to mount the sub-mount point.
```
curl --unix-socket api.sock \
     -X POST "http://localhost/api/v1/mount?mountpoint=/sub" \
     -H "Content-Type: application/json" \
     -d '{
        "source":"bootstrap-test",
        "fs_type":"rafs",
        "config":"{\"device\":{\"backend\":{\"type\":\"localfs\",\"config\":{\"dir\":\"blobs\"}},\"cache\":{\"type\":\"blobcache\",\"config\":{\"work_dir\":\"cache\"}}},\"mode\":\"direct\",\"digest_validate\":false}"
	}'
```
Observe the number of threads of the nydusd process after mount:
![2](https://github.com/user-attachments/assets/d015750f-7da7-433d-b7b8-f5e0b0e7c968)
## 4. Umount sub mount point.
```
curl --unix-socket api.sock \
     -X DELETE "http://localhost/api/v1/mount?mountpoint=/sub"
```
Observe the number of threads of the nydusd process after umount:
![3](https://github.com/user-attachments/assets/5d77b708-c414-4085-9b70-bcb108846cc5)
# Result:
After mount, the nydusd process creates two cache-flusher threads but only recycles one with umount.

**Comment by Desiki-high** [comment]
After testing again, the two `cache-flusher` threads include one manage thread used by tokio]mutil threads runtime and one work thread. The work thread had been recycled by tokio runtime. I also tested the memory used with thousands of mounts and unmounts. There has been no thread/memory leak.
