### ISSUE TITLE
Counseling：I want to save the nydus image converted by nydusify convert --source --target to the current directory. How can I do that?

### ISSUE THREAD

**Issue by mnwyl123** [dragonflyoss/nydus#1580]
I want to save the nydus image converted by nydusify convert --source --target to the current directory. How can I do that?

**Comment by imeoer** [comment]
Hi, it's a planned feature: https://github.com/dragonflyoss/nydus/issues/1576#issuecomment-2133215611

**Comment by imeoer** [comment]
dup with https://github.com/dragonflyoss/nydus/issues/1576#issuecomment-2133215611
