### ISSUE TITLE
GitHub wiki has broken link for nydus tutorial

### ISSUE THREAD

**Issue by ryansavino** [dragonflyoss/nydus#1581]
The wiki has a broken link for the nydus tutorial:
https://github.com/dragonflyoss/nydus/wiki

Link:
https://github.com/dragonflyoss/image-service/docs/tutorial.md

**Comment by Desiki-high** [comment]
Thank you for your report. Since https://github.com/dragonflyoss/nydus/pull/1435, we have removed `tutorial.md` . I have updated wiki.
