### ISSUE TITLE
Whether to support outputting metadata files when nydus convert

### ISSUE THREAD

**Issue by dyume99** [dragonflyoss/nydus#1593]
Hi, I'm using nydus convert like:
```
nydusify convert  --nydus-image nydus-image --source /path/to/source_image --target /path/to/target_image
```
and I'm wondering if there is a way to output the metadata file of the target image like parameters in buildkit:
```
buildctl build --metadata-file /path/to/metadata_file
```
If it is not supported currently, I would like to ask if there is a convenient way to get the digest of the target nydus image. 
Thank you very much!

**Comment by imeoer** [comment]
Hi, maybe try `docker manifest inspect -v $target_image`, the image digest should in field `.Descriptor.digest`.

**Comment by dyume99** [comment]
> Hi, maybe try `docker manifest inspect -v $target_image`, the image digest should in field `.Descriptor.digest`.

Got it, thank you very much!
