### ISSUE TITLE
nydusify commit operation only be supported in default namespace

### ISSUE THREAD

**Issue by shusley244** [dragonflyoss/nydus#1596]
when I exec command: `nydusify commit --container 6e852f9d0b9f --target xxxx`, it returns `inspect container: load container: container "6e852f9d0b9f" in namespace "default": not found`. 

I am using k8s and container namespace is `k8s.io`, I think nydusify commit operation should add global flag to set namespace like `nerdctl -n k8s.io`.

```
Nydusify version
Version : v2.3.0-alpha.2
Revision        : 332f3dd4561019546598b06b8092a3d2f45e8786
Go version      : go1.21.11
Build time      : 2024-06-19T10:33:03
```

**Comment by imeoer** [comment]
Thanks for the report, submit a PR if you are interested. :) cc @PerseidMeteor .

**Comment by PerseidMeteor** [comment]
> Thanks for the report, submit a PR if you are interested. :) cc @PerseidMeteor .

https://github.com/dragonflyoss/nydus/pull/1597 :)
