### ISSUE TITLE
Not able to run nydus image with nerdctl

### ISSUE THREAD

**Issue by gane5hvarma** [dragonflyoss/nydus#1621]
## Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

### Version of nydus being used (nydusd --version)

Version: 	v2.3.0-rc.0
Git Commit: 	3eb5c7b5ef90383fa6e966d37ecfac9313702a58
Build Time: 	2024-08-28T03:14:19.161229388Z
Profile: 	release
Rustc: 		rustc 1.72.1 (d5c2e9c34 2023-09-13)

### Version of nydus-snapshotter being used (containerd-nydus-grpc --version)

Version:     v0.14.0
Revision:    8e72f94dcad2d4898b6437fc84d6c9c36f78ea50
Go version:  go1.21.12
Build time:  2024-08-02T06:25:41

### Kernel information (uname -r)
_command result: uname -r_
6.1.106-116.188.amzn2023.x86_64

### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_
NAME="Amazon Linux"

### containerd-nydus-grpc command line used, if applicable (ps aux | grep containerd-nydus-grpc)
```
./containerd-nydus-grpc --config /etc/nydus/config.toml --log-to-stdout
```

### client command line used, if applicable (such as: nerdctl, docker, kubectl, ctr)
```
nerdctl --snapshotter nydus run gane5h/build_tool:llmnydus
```

## Details about issue
Hi, I have built a docker image of size 30 gb. I converted the docker image to nydus image using nydusify. Once the image is converted i tried checking with nydusify check. it reported no issues. 
After that i tried running below command. It failed with mount callback failed error. Im not sure on how to debug this error
```
nerdctl --snapshotter nydus run gane5h/build_tool:llmnydus
```
logs:
```
FATA[0015] mount callback failed on /tmp/containerd-mount2765718767: read /tmp/containerd-mount2765718767/etc/group: invalid argument
```

**Comment by Desiki-high** [comment]
Hi @gane5hvarma , pLease follow https://github.com/dragonflyoss/nydus/blob/master/docs/containerd-env-setup.md to setup nydus snapshotter as Containerd(1.x) global snapshotter. And use containerd-nydus-grpc v0.13.13 first. In that case you can check the full log in /var/lib/containerd-nydus/los/nydus-snapshotter.log.

**Comment by gane5hvarma** [comment]
Hi @Desiki-high, i followed the doc. I tried testing with the ubuntu image mentioned in above doc. Seeing this error in continerd-nydus-grpc after running 
```
sudo nerdctl --snapshotter nydus run --rm localhost:5000/redis-nydus
```


```

INFO[2024-09-16T17:58:09.645805498Z] [Mounts] snapshot default/223/f610922354f3f097f1620c8ff811e00ae78119ec36b2b3621dce55589959d495 ID 196 Kind Active
INFO[2024-09-16T17:58:09.645863089Z] remote mount options [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/196/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/196/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/172/mnt]
[2024-09-16 17:58:09.647596 +00:00] ERROR [/src/error.rs:23] Error:
	"failed to get chunk information"
	at rafs/src/metadata/direct_v6.rs:828
	note: enable `RUST_BACKTRACE=1` env to display a backtrace
[2024-09-16 17:58:09.647802 +00:00] ERROR [/src/error.rs:23] Error:
	"failed to get chunk information"
	at rafs/src/metadata/direct_v6.rs:828
	note: enable `RUST_BACKTRACE=1` env to display a backtrace
INFO[2024-09-16T17:58:09.880581405Z] [Remove] snapshot with key default/223/f610922354f3f097f1620c8ff811e00ae78119ec36b2b3621dce55589959d495 snapshot id 196
INFO[2024-09-16T17:58:09.883112498Z] [Cleanup] orphan directories [/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/196]

```

**Comment by gane5hvarma** [comment]
Also when i try to run the below command, it works perfectly fine. The image is from nydus image repo

```
nerdctl --snapshotter nydus run ghcr.io/dragonflyoss/nydus/redis:nydus-nightly-oci-ref
```

**Comment by Desiki-high** [comment]
You can try [nydus v2.2.5](https://github.com/dragonflyoss/nydus/releases/tag/v2.2.5) include `nydusd`, `nydus-image` and `nydusify`. And use image `ghcr.io/dragonflyoss/nydus/redis:nydus-nightly-v6` and `ghcr.io/dragonflyoss/nydus/redis:nydus-nightly-v5`, the `redis:nydus-nightly-oci-ref` is a special version of [zran](https://github.com/dragonflyoss/nydus/blob/master/docs/nydus-zran.md).

**Comment by Desiki-high** [comment]
Please also check the log: `/var/lib/containerd/io.containerd.snapshotter.v1.nydus/logs/xxxx/nydusd_rCurrent.log` when you run a container with nydus sanpshotter. It is the log file of nydusd.

**Comment by gane5hvarma** [comment]
Hi @Desiki-high, I did a fresh install of all the above components in a different machine. Things are working now as expected, Im  able to run nydus images. Thank you

**Comment by gane5hvarma** [comment]
Hi @Desiki-high, I have restarted my container. After i restarted i ran containerd-nydus-grpc, i got this error
```
failed to initialize snapshotter: create database: timeout
```

**Comment by gane5hvarma** [comment]
I mean rebooted my node and restarted `containerd-nydus-grpc`

**Comment by imeoer** [comment]
> failed to initialize snapshotter: create database: timeout
> ```

@gane5hvarma It looks like another `containerd-nydus-grpc` process is running?

**Comment by gane5hvarma** [comment]
@imeoer yes another process of containerd-nydus-grpc is running in background. I will keep this mind going forward.
Also im trying to deploy nydus-snapshotter in kubernetes. I have followed this guide https://github.com/dragonflyoss/helm-charts/blob/main/INSTALL.md#install-nydus-based-on-helm-charts, when i tried to apply this pod spec
https://github.com/dragonflyoss/helm-charts/blob/main/INSTALL.md#run-nydus-image-in-kubernetes. The pod got stuck in containerCreating stage. This is the error which i got from describing pod
```
Failed to create pod sandbox: rpc error: code = NotFound desc = failed to create containerd container: error unpacking image: failed to extract layer sha256:59b1469b8fbd05fd256959ad9d7d776b9937b848d75113a0d7c1af442528b6d0: failed to get reader from content store: content digest sha256:0692f38991d53a0c28679148f99de26a44d630fda984b41f63c5e19f839d15a6: not found
```

**Comment by imeoer** [comment]
> Failed to create pod sandbox: rpc error: code = NotFound desc = failed to create containerd container: error unpacking image: failed to extract layer sha256:59b1469b8fbd05fd256959ad9d7d776b9937b848d75113a0d7c1af442528b6d0: failed to get reader from content store: content digest sha256:0692f38991d53a0c28679148f99de26a44d630fda984b41f63c5e19f839d15a6: not found

@gane5hvarma PTAL https://github.com/dragonflyoss/nydus/wiki/FAQ#q-cant-start-nydus-pod-in-k8s-error-failed-to-get-reader-from-content-store-content-digest-sha256-not-found

**Comment by gane5hvarma** [comment]
@imeoer thanks for the help. After fetching the pause image pod was created and running
