### ISSUE TITLE
Can Nydus set asynchronous on-demand fetching to full volume fetching?

### ISSUE THREAD

**Issue by Jaycean** [dragonflyoss/nydus#1628]
I would like to use Nydus now. There is a scenario where I need to pull all the block data and not use lazy loading. I want to know how to configure this, as I haven't found the relevant configuration in the documentation.

**Comment by imeoer** [comment]
What is the scenario? Why don't we use the OCI v1 image.

**Comment by Jaycean** [comment]
> What is the scenario? Why don't we use the OCI v1 image.

We used Nydus because it allows us to save more space by deduplicating through blocks. However, we are concerned that it may affect our business in extreme network environments, so we want to pull it first before running the container
