### ISSUE TITLE
How about just naming this project NYDUS rather than image service?

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/nydus#469]
Like the title, I think almost everyone knows nydus:
* https://nydus.dev/
* the introduction in the project
* and some others
while the project name is image-service. It is quite weird. 

How about just naming this project NYDUS rather than image service? @dragonflyoss/dragonfly2-maintainers

**Comment by imeoer** [comment]
Couldn't agree more. cc @bergwolf

**Comment by hsiangkao** [comment]
can we have some progress on this stuff?

**Comment by adamqqqplay** [comment]
LGTM, but needs further discussion. cc @bergwolf

**Comment by imeoer** [comment]
Thanks! It's done.
