### ISSUE TITLE
Need to be fixed for docker graph driver 

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/nydus#672]
We made a [graph driver plugin](https://github.com/dragonflyoss/image-service/tree/master/contrib/docker-nydus-graphdriver) to support nydus image for docker, but it is still not ready for production usage.

The problem we know with this graph driver is that the blob layers are not referenced by the image manifest, so they may be registry GC-ed.

A workaround is to make a manifest index that included two manifests, the first one only references the bootstrap, and the second one only references the blobs. In this way, docker will only pull the first manifest and the bootstrap layer.

- [ ] Support manifest index included two types of manifest by nydusify/acceld.

**Comment by changweige** [comment]
Can you list potential tasks to achieve the goal you mentioned? So we can carry on.

**Comment by imeoer** [comment]
@changweige Updated, just one thing.

**Comment by imeoer** [comment]
Let's try use containerd snapshotter in latest docker release.
