### ISSUE TITLE
support s3 storage backend

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/nydus#831]
Currently nydus only supports Aliyun OSS, we need to support more object storage backends, for example AWS S3, the following components need to be supported:

- [x] nydusify
- [ ] acceld
- [x] nydusd

**Comment by loheagn** [comment]
Hi, @imeoer, I want to take this issue. Can you assign it to me?

**Comment by imeoer** [comment]
@loheagn Cool, let's move forward!

**Comment by CSUDaXiang** [comment]
hello,Have you made any progress on this issue recently?

**Comment by loheagn** [comment]
Hi, @imeoer @CSUDaXiang , I opened a PR to add s3 support to `nydusify convert`. For more information, please refer to the PR #871.

The next target is to add s3 support to nydusd.
