### ISSUE TITLE
Bug: get errors when converting nydus image

### ISSUE THREAD

**Issue by sctb512** [dragonflyoss/nydus#846]
Error 1:
![1cd46a5d-e397-46d7-9290-281d654cb141](https://user-images.githubusercontent.com/20137756/200319328-69d2e4fd-a0a9-4d6d-a110-61da5a045b4b.jpeg)
Command:
```shell
sudo /usr/local/bin/nydusify convert \
--fs-version 6  \
--nydus-image /usr/local/bin/nydus-image \
--source xxx \
--target xxx
```
version:
```shell
❯ nydus-image --version
Version:        v2.1.0-10-g36b4edb6
Git Commit:     36b4edb638f0f2c11e95641e3920866bddfad7bc
Build Time:     2022-11-07T12:27:38.562973044Z
Profile:        release
Rustc:          rustc 1.61.0 (fe5b13d68 2022-05-18)

❯ nydusify --version
Nydusify version 36b4edb638f0f2c11e95641e3920866bddfad7bc.20221107.1159
```

This error occurred by accident. When i run the same command again, it converts the OCI image to nydus image successfully.

Error 2:
![79c4f0be-b1aa-4296-9662-d32924a5e23a](https://user-images.githubusercontent.com/20137756/200320222-d5f7006f-72df-4016-9330-324915d12040.jpeg)

version:
```shell
❯ nydus-image --version
Version:        v2.1.0-10-g36b4edb6
Git Commit:     36b4edb638f0f2c11e95641e3920866bddfad7bc
Build Time:     2022-11-07T12:27:38.562973044Z
Profile:        release
Rustc:          rustc 1.61.0 (fe5b13d68 2022-05-18)

❯ nydusify --version
Nydusify version 752b72be9dbd901140a8e9ec30600209c06221b7.20221107.1324
```
I find a `401 response` when pushing blob data. Maybe it is related to this error?

**Comment by imeoer** [comment]
@sctb512 Is this OCI image can convert by acceld?

**Comment by imeoer** [comment]
No more cases reproduce for now, reopen it if necessary.
